- name: Provisiong ec2 instances
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars.yml

  tasks:
    - name: Provision a set of instances
      ec2:
        key_name: "{{ key_name }}"
        group_id: "{{ group_id }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        count: "{{ cluster_size }}"
        assign_public_ip: yes
        instance_tags: "{{ tags }}"
      register: ec2

    - name: Add instances to a host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances

    - name: Wait for SSH
      pause: minutes=1

- name: Configure launched instance
  hosts: launched
  vars_files:
    - vars.yml
  user: "{{ ec2_user }}"
  sudo: True
  gather_facts: True

  roles:
    - common
    - supervisor
    - zookeeper
    - exhibitor
