---
- name: Install Zookeeper and Exhibitor
  hosts: "{{ hosts }}"
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Install Required Packages
      sudo: true
      apt:
        update_cache: true
        pkg: "{{ item }}"
        state: present
      with_items:
        - wget
        - supervisor
        - openjdk-7-jdk

    - name: Stop service
      sudo: true
      supervisorctl: name="exhibitor" state=stopped

  roles:
    - zookeeper
    - exhibitor

  post_tasks:
    - name: Reread supervisor
      sudo: true
      command: supervisorctl reread

    - name: Update supervisor
      sudo: true
      command: supervisorctl update

    - name: Restart service
      sudo: true
      supervisorctl: name="exhibitor" state=restarted
