---
- name: Create Directory
  file: 
    path: "{{ exhibitor.dir}}"
    owner: "{{exhibitor.user}}"
    group: "{{exhibitor.group}}"
    mode: 0755 
    state: directory

- name: Create Data Directory
  file:
    path: "{{exhibitor.data_dir}}"
    owner: "{{exhibitor.user}}"
    group: "{{exhibitor.group}}"
    mode: 0755
    state: directory

- name: Copy Exhibitor JAR
  copy: 
    src: "exhibitor-{{exhibitor.version}}.jar"
    dest: "{{exhibitor.dir}}/exhibitor.jar"
    owner: "{{exhibitor.user}}"
    group: "{{exhibitor.group}}"

- name: Set exhibitor.cfg
  template:
    src: exhibitor.cfg.j2 
    dest: "{{ exhibitor.dir }}/exhibitor.cfg"
    owner: "{{ exhibitor.user }}"
    group: "{{ exhibitor.group }}"

- name: Add supervisor config
  template:
    src: supervisor.exhibitor.conf.j2
    dest: /etc/supervisor/conf.d/exhibitor.conf
    owner: "{{ exhibitor.user }}"
    group: "{{ exhibitor.group }}"
