---
- name: Install JDK
  apt: name=openjdk-7-jre-headless state=present

- name: Create Directory
  file: path={{exhibitor_install_dir}} owner={{exhibitor_user}} group={{exhibitor_group}} mode=0755 state=directory

- name: Create Data Directory
  file: path={{exhibitor_install_dir}}/data owner={{exhibitor_user}} group={{exhibitor_group}} mode=0755 state=directory

- name: Copy Exhibitor JAR
  copy: src=exhibitor-1.5.5.jar dest={{exhibitor_install_dir}}/exhibitor.jar owner={{exhibitor_group}} group={{exhibitor_group}}

- name: Add supervisor config
  template: >
    src=exhibitor.conf.j2
    dest=/etc/supervisor/conf.d/exhibitor.conf
    owner={{ exhibitor_user }}
    group={{ exhibitor_group }}

- name: Restart supervisor
  shell: supervisorctl reread && supervisorctl update
